### ISSUE TITLE
VPS // Apache error.log flooding from redmine

### ISSUE THREAD

**Issue by khanon** [scaleway-community/scaleway-redmine#14] opened 2016-03-31 23:32 UTC
Running on a scaleway VPS server, with standard redmine image. The image's default redmine settings flood Apache's error.log it seems.

Snippet from apache2/error.log

```
App 10893 stderr: ActionController::RoutingError (No route matches [GET] "/null"):
App 10893 stderr:   actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 10893 stderr:   actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 10893 stderr:   railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
App 10893 stderr:   railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
App 10893 stderr:   activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 10893 stderr:   activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
App 10893 stderr:   activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
App 10893 stderr:   railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
App 10893 stderr:   actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 10893 stderr:   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
App 10893 stderr:   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
App 10893 stderr:   activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
App 10893 stderr:   actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
App 10893 stderr:   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
App 10893 stderr:   railties (4.2.3) lib/rails/engine.rb:518:in `call'
App 10893 stderr:   railties (4.2.3) lib/rails/application.rb:165:in `call'
App 10893 stderr:   railties (4.2.3) lib/rails/railtie.rb:194:in `public_send'
App 10893 stderr:   railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing'
App 10893 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
App 10893 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
App 10893 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 10893 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
```

**Comment by moul** [comment] 2016-04-01 07:41
@bchatelard I know you're not a redmine guru, but your ruby skill may help to understand what could be the cause of the failure here ?

**Comment by bchatelard** [comment] 2016-04-01 07:55
@khanon how can we reproduce this ?

It looks like a software bug.

**Comment by bchatelard** [comment] 2016-04-01 09:04
I am not sure why you have a lot of query to the '/null' url.

The error message is not a real error, it just mean that the endpoint is not found and that a 404 will be raised.

**Comment by bchatelard** [comment] 2017-03-23 16:32
This issue should be fixed

**Closed by bchatelard** 2017-03-23 16:32 UTC
Labels: bug
